import { useRouter } from 'next/router'
import { createClient } from "next-sanity";
import PortableText from 'react-portable-text';
import Head from 'next/head';
import imageUrlBuilder from '@sanity/image-url'
const Post = ({ blog, author }) => {
    const router = useRouter()
    const { slug } = router.query


    const client = createClient({
        projectId: "puehhpql",
        dataset: "production",
        useCdn: false
    });


    const builder = imageUrlBuilder(client)

   
    return (
        <>

            <Head>
                <title>{blog.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />

            </Head>
            <div className='sm:pt-[6rem] rounded-b-[5rem]'>
                <main className="pt-8 pb-16 lg:pt-16 lg:pb-24 bg-gray-900">
                    <div className="flex justify-between px-4 mx-auto max-w-screen-xl ">
                        <article className="mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert">
                            <header className="mb-4 lg:mb-6 not-format">
                                <h1 className="mb-4 text-3xl font-bold leading-tight text-gray-900 lg:mb-6 lg:text-4xl dark:text-white">{blog.title}</h1>
                                <address className="flex items-center mb-6 not-italic ">
                                    <div className="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white">
                                        <img className="mr-4 w-16 h-16 rounded-full" src={builder.image(author.image).width(200).url()} alt={author.name} />
                                        <div>
                                            <a href="#" rel="author" className="text-xl font-bold text-gray-900 dark:text-white">{author.authorname}</a>
                                            <p className="text-base font-light text-gray-500 dark:text-gray-400">{author.decs}</p>
                                            {/* <p className="text-base font-light text-gray-500 dark:text-gray-400"><time dateTime="2022-02-08" title="February 8th, 2022" pubdate="true">{author._createdAt.slice(0, 10)}</time></p> */}
                                        </div>
                                    </div>
                                </address>

                            </header>

                            <p className='md:text-2xl'>{blog.metadesc}</p>

                            <img src={builder.image(blog.blogimage).width(800).url()} alt="Blog-Image" className='my-5' />


                            <PortableText

                                content={blog.content}
                                projectId="puehhpql"
                                dataset="production"
                                className="md:text-2xl"

                            />


                        </article>
                    </div>
                </main>

                {/* <aside aria-label="Related articles" className="py-8 lg:py-24 bg-gray-50 dark:bg-gray-800">
                <div className="px-4 mx-auto max-w-screen-xl">
                    <h2 className="mb-8 text-2xl font-bold text-gray-900 dark:text-white">Related articles</h2>
                    <div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-4">
                        <article className="max-w-xs">
                            <a href="#">
                                <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/article/blog-1.png" className="mb-5 rounded-lg" alt="Image 1" />
                            </a>
                            <h2 className="mb-2 text-xl font-bold leading-tight text-gray-900 dark:text-white">
                                <a href="#">Our first office</a>
                            </h2>
                            <p className="mb-4 font-light text-gray-500 dark:text-gray-400">Over the past year, Volosoft has undergone many changes! After months of preparation.</p>
                            <a href="#" className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline">
                                Read in 2 minutes
                            </a>
                        </article>
                        <article className="max-w-xs">
                            <a href="#">
                                <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/article/blog-2.png" className="mb-5 rounded-lg" alt="Image 2" />
                            </a>
                            <h2 className="mb-2 text-xl font-bold leading-tight text-gray-900 dark:text-white">
                                <a href="#">Enterprise design tips</a>
                            </h2>
                            <p className="mb-4 font-light text-gray-500 dark:text-gray-400">Over the past year, Volosoft has undergone many changes! After months of preparation.</p>
                            <a href="#" className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline">
                                Read in 12 minutes
                            </a>
                        </article>
                        <article className="max-w-xs">
                            <a href="#">
                                <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/article/blog-3.png" className="mb-5 rounded-lg" alt="Image 3" />
                            </a>
                            <h2 className="mb-2 text-xl font-bold leading-tight text-gray-900 dark:text-white">
                                <a href="#">We partnered with Google</a>
                            </h2>
                            <p className="mb-4 font-light text-gray-500 dark:text-gray-400">Over the past year, Volosoft has undergone many changes! After months of preparation.</p>
                            <a href="#" className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline">
                                Read in 8 minutes
                            </a>
                        </article>
                        <article className="max-w-xs">
                            <a href="#">
                                <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/article/blog-4.png" className="mb-5 rounded-lg" alt="Image 4" />
                            </a>
                            <h2 className="mb-2 text-xl font-bold leading-tight text-gray-900 dark:text-white">
                                <a href="#">Our first project with React</a>
                            </h2>
                            <p className="mb-4 font-light text-gray-500 dark:text-gray-400">Over the past year, Volosoft has undergone many changes! After months of preparation.</p>
                            <a href="#" className="inline-flex items-center font-medium underline underline-offset-4 text-primary-600 dark:text-primary-500 hover:no-underline">
                                Read in 4 minutes
                            </a>
                        </article>
                    </div>
                </div>
            </aside> */}





            </div>
        </>)
}

export default Post

export async function getServerSideProps(context) {
    const { slug } = context.query;
    // console.log(slug);



    const client = createClient({
        projectId: "puehhpql",
        dataset: "production",
        useCdn: false
    });
    const query = `*[_type == "blog" && slug.current == '${slug}'][0]`;
    const blog = await client.fetch(query);

    const authorquery = `*[_type == "author"][1]`;
    const author = await client.fetch(authorquery);


    // console.log(blog);


    return {
        props: {
            blog, author

        }
    }
}