import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from './Hero';
import About from './About';
import Skills from './Skills';
import Experience from './Experience';
import Projects from './Projects';
import Contact from './Contact';
import Technology from './Technology';
import Footer from './components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Harshal Kahar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero></Hero>
        <About></About>
        <Skills></Skills>
        <Experience></Experience>
        {/* <Projects></Projects> */}
        <Contact></Contact>
        <Technology></Technology>

        <Footer></Footer>
      </main>
    </>


  )
}
