import Head from 'next/head'
import Hero from './Hero';
import About from './About';
import Skills from './Skills';
import Experience from './Experience';
import Contact from './Contact';
import Technology from './Technology';
import Footer from './components/Footer';
import Quotes from './components/Quotes';
import { createClient } from "next-sanity";
import imageUrlBuilder from '@sanity/image-url';
import Blogs from './Blogs';
import Projects from './Pro';

export default function Home({ blogs, profile, skills, technology, programming, development, others, experience, project }) {

  const client = createClient({
    projectId: "puehhpql",
    dataset: "production",
    useCdn: false
  });
  const builder = imageUrlBuilder(client);

  return (
    <>
      <Head>
        <title>Harshal Kahar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />

      </Head>
      <main>
        <Hero profile={profile}></Hero>
        <About profile={profile}></About>
        <Skills skills={skills} technology={technology} development={development} programming={programming} others={others}></Skills>
        <Experience experience={experience}></Experience>
        <Projects project={project}></Projects>
        <Blogs blogs={blogs}></Blogs>
        <Contact></Contact>
        <Quotes></Quotes>
        <Technology></Technology>
        <Footer></Footer>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const client = createClient({
    projectId: "puehhpql",
    dataset: "production",
    useCdn: false
  });
  const query = `*[_type == "blog"]`;
  const blogs = await client.fetch(query);

  const profileQuery = `*[_type == "profile"][0]`;
  const profile = await client.fetch(profileQuery);

  const skillsQuery = `*[_type == "skills"][0]`;
  const skills = await client.fetch(skillsQuery);

  const Technologyquery = `*[_type == "technology"]`;
  const technology = await client.fetch(Technologyquery);

  const Programmingquery = `*[_type == "programming"]`;
  const programming = await client.fetch(Programmingquery);

  const Developmentquery = `*[_type == "development"]`;
  const development = await client.fetch(Developmentquery);

  const Others = `*[_type == "others"]`;
  const others = await client.fetch(Others);

  const Experiencequery = `*[_type == "experience"]`;
  const experience = await client.fetch(Experiencequery);

  const Projectquery = `*[_type == "project"]`;
  const project = await client.fetch(Projectquery);

  return {
    props: {
      blogs, profile, skills, technology, programming, development, others, experience, project

    }
  }
}



